export const cars = [
  {
    name: "main.cars.audiA8.name",
    price: "$80,000",
    image: "/Images/Store/Audi A8 2022.jpg",
    images: {
      0: "/Images/Store/Audi A8 2022.jpg",
      1: "/Images/Store/Audi A8 2022 1.jpg",
      2: "/Images/Store/Audi A8 2022 2.jpg",
      3: "/Images/Store/Audi A8 2022 3.jpg",
      4: "/Images/Store/Audi A8 2022 4.jpg",
      5: "/Images/Store/Audi A8 2022 5.jpg",
    },
    year: "2022",
    engine: "main.cars.audiA8.engine",
    transmission: "main.cars.audiA8.transmission",
    mileage: "main.cars.audiA8.mileage",
    status: "main.cars.audiA8.status",
  },
  {
    name: "main.cars.bmwM4.name",
    price: "$60,000",
    image: "/Images/Store/BMW M4 2018.jpg",
    images: {
      0: "/Images/Store/BMW M4 2018.jpg",
      1: "/Images/Store/BMW M4 2018 1.jpg",
      2: "/Images/Store/BMW M4 2018 2.jpg",
      3: "/Images/Store/BMW M4 2018 3.jpg",
      4: "/Images/Store/BMW M4 2018 4.jpg",
      5: "/Images/Store/BMW M4 2018 5.jpg",
    },
    year: "2018",
    engine: "main.cars.bmwM4.engine",
    transmission: "main.cars.bmwM4.transmission",
    mileage: "main.cars.bmwM4.mileage",
    status: "main.cars.bmwM4.status",
  },
  {
    name: "main.cars.hyundaiTucson.name",
    price: "$18,000",
    image: "/Images/Store/Hyundai Tucson 2019.jpg",
    images: {
      0: "/Images/Store/Hyundai Tucson 2019.jpg",
      1: "/Images/Store/Hyundai Tucson 2019 1.jpg",
      2: "/Images/Store/Hyundai Tucson 2019 2.jpg",
      3: "/Images/Store/Hyundai Tucson 2019 3.jpg",
      4: "/Images/Store/Hyundai Tucson 2019 4.jpg",
      5: "/Images/Store/Hyundai Tucson 2019 5.jpg",
    },
    year: "2019",
    engine: "main.cars.hyundaiTucson.engine",
    transmission: "main.cars.hyundaiTucson.transmission",
    mileage: "main.cars.hyundaiTucson.mileage",
    status: "main.cars.hyundaiTucson.status",
  },
  {
    name: "main.cars.hyundaiPalisade.name",
    price: "$47,000",
    image: "/Images/Store/Hyundai Palisade 2023.jpg",
    images: {
      0: "/Images/Store/Hyundai Palisade 2023.jpg",
      1: "/Images/Store/Hyundai Palisade 2023 1.jpg",
      2: "/Images/Store/Hyundai Palisade 2023 2.jpg",
      3: "/Images/Store/Hyundai Palisade 2023 3.jpg",
      4: "/Images/Store/Hyundai Palisade 2023 4.jpg",
      5: "/Images/Store/Hyundai Palisade 2023 5.jpg",
    },
    year: "2023",
    engine: "main.cars.hyundaiPalisade.engine",
    transmission: "main.cars.hyundaiPalisade.transmission",
    mileage: "main.cars.hyundaiPalisade.mileage",
    status: "main.cars.hyundaiPalisade.status",
  },
  {
    name: "main.cars.kiaSorento.name",
    price: "$25,000",
    image: "/Images/Store/Kia Sorento 2021.jpg",
    images: {
      0: "/Images/Store/Kia Sorento 2021.jpg",
      1: "/Images/Store/Kia Sorento 2021 1.jpg",
      2: "/Images/Store/Kia Sorento 2021 2.jpg",
      3: "/Images/Store/Kia Sorento 2021 3.jpg",
      4: "/Images/Store/Kia Sorento 2021 4.jpg",
      5: "/Images/Store/Kia Sorento 2021 5.jpg",
    },
    year: "2021",
    engine: "main.cars.kiaSorento.engine",
    transmission: "main.cars.kiaSorento.transmission",
    mileage: "main.cars.kiaSorento.mileage",
    status: "main.cars.kiaSorento.status",
  },
  {
    name: "main.cars.mercedesCLS.name",
    price: "$54,000",
    image: "/Images/Store/Mercedes-Benz CLS 2019.jpg",
    images: {
      0: "/Images/Store/Mercedes-Benz CLS 2019.jpg",
      1: "/Images/Store/Mercedes-Benz CLS 2019 1.jpg",
      2: "/Images/Store/Mercedes-Benz CLS 2019 2.jpg",
      3: "/Images/Store/Mercedes-Benz CLS 2019 3.jpg",
      4: "/Images/Store/Mercedes-Benz CLS 2019 4.jpg",
      5: "/Images/Store/Mercedes-Benz CLS 2019 5.jpg",
    },
    year: "2019",
    engine: "main.cars.mercedesCLS.engine",
    transmission: "main.cars.mercedesCLS.transmission",
    mileage: "main.cars.mercedesCLS.mileage",
    status: "main.cars.mercedesCLS.status",
  },
];